// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { supabase } from './client'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function runtimeLog(stage: 'ADMIN_AUTH' | 'SUPABASE_SERVER_CONFIG', reason: string, error?: unknown) {
  console.error('[Virelia runtime]', {
    stage,
    reason,
    message: error instanceof Error ? error.message.slice(0, 240) : undefined,
  });
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' })
  .client(async ({ next }) => {
    // Server functions do not inherit the Supabase session stored in localStorage.
    // Forward the user's access token explicitly so protected admin functions can authenticate.
    try {
      const { data, error } = await supabase.auth.getSession();
      if (error) {
        runtimeLog('ADMIN_AUTH', 'client_session_read_failed', error);
        return next();
      }
      const token = data.session?.access_token;
      if (!token) return next();
      return next({
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
    } catch (error) {
      runtimeLog('ADMIN_AUTH', 'client_token_forward_failed', error);
      return next();
    }
  })
  .server(async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL/VITE_SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY
          ? ['SUPABASE_PUBLISHABLE_KEY/VITE_SUPABASE_PUBLISHABLE_KEY']
          : []),
      ];
      runtimeLog('SUPABASE_SERVER_CONFIG', `missing:${missing.join(',')}`);
      throw new Error('server_configuration_missing');
    }

    const request = getRequest();
    if (!request?.headers) {
      runtimeLog('ADMIN_AUTH', 'request_headers_unavailable');
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      runtimeLog('ADMIN_AUTH', 'missing_bearer_token');
      throw new Error('Unauthorized: Missing bearer token');
    }

    const token = authHeader.slice('Bearer '.length).trim();
    if (!token || token.split('.').length !== 3) {
      runtimeLog('ADMIN_AUTH', 'invalid_bearer_token_shape');
      throw new Error('Unauthorized: Invalid token');
    }

    const serverClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        headers: { Authorization: `Bearer ${token}` },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await serverClient.auth.getClaims(token);
    if (error || !data?.claims?.sub) {
      runtimeLog('ADMIN_AUTH', 'token_claims_rejected', error);
      throw new Error('Unauthorized: Invalid token');
    }

    return next({
      context: {
        supabase: serverClient,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  });
